-- Smart Khata PostgreSQL database schema
-- Target: Railway PostgreSQL
-- Version: 001

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- 1. SaaS users and businesses
-- =========================================================

CREATE TABLE app_users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),

  full_name VARCHAR(150) NOT NULL,
  phone_number VARCHAR(30),
  email VARCHAR(150),
  password_hash TEXT NOT NULL,
  profile_image_url TEXT,

  is_super_admin BOOLEAN NOT NULL DEFAULT FALSE,
  is_support_admin BOOLEAN NOT NULL DEFAULT FALSE,

  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
  is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,

  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_app_users_public_id ON app_users(public_id);
CREATE UNIQUE INDEX ux_app_users_email_active ON app_users(LOWER(email)) WHERE email IS NOT NULL AND is_deleted = FALSE;
CREATE UNIQUE INDEX ux_app_users_phone_active ON app_users(phone_number) WHERE phone_number IS NOT NULL AND is_deleted = FALSE;

CREATE TRIGGER trg_app_users_updated_at
BEFORE UPDATE ON app_users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE businesses (
  business_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id BIGINT NOT NULL REFERENCES app_users(user_id),

  business_name VARCHAR(200) NOT NULL,
  business_type VARCHAR(100),
  phone_number VARCHAR(30),
  whatsapp_number VARCHAR(30),
  email VARCHAR(150),
  address TEXT,
  city VARCHAR(100),
  country VARCHAR(100) NOT NULL DEFAULT 'Pakistan',

  logo_url TEXT,
  ntn VARCHAR(50),
  strn VARCHAR(50),

  currency_code VARCHAR(10) NOT NULL DEFAULT 'PKR',
  timezone VARCHAR(100) NOT NULL DEFAULT 'Asia/Karachi',

  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
  block_reason TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_businesses_public_id ON businesses(public_id);
CREATE INDEX ix_businesses_owner_user_id ON businesses(owner_user_id);

CREATE TRIGGER trg_businesses_updated_at
BEFORE UPDATE ON businesses
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE roles (
  role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(100) NOT NULL,
  role_code VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,
  is_system_role BOOLEAN NOT NULL DEFAULT TRUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE permissions (
  permission_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission_code VARCHAR(100) NOT NULL UNIQUE,
  permission_name VARCHAR(150) NOT NULL,
  module_name VARCHAR(100) NOT NULL,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE role_permissions (
  role_permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id INT NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
  permission_id INT NOT NULL REFERENCES permissions(permission_id) ON DELETE CASCADE,
  UNIQUE(role_id, permission_id)
);

CREATE TABLE business_users (
  business_user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES app_users(user_id),
  role_id INT NOT NULL REFERENCES roles(role_id),

  is_owner BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  can_login BOOLEAN NOT NULL DEFAULT TRUE,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

  UNIQUE(business_id, user_id)
);

CREATE INDEX ix_business_users_user_id ON business_users(user_id);
CREATE INDEX ix_business_users_business_id ON business_users(business_id);

CREATE TRIGGER trg_business_users_updated_at
BEFORE UPDATE ON business_users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE business_invitations (
  invitation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  invited_email VARCHAR(150),
  invited_phone_number VARCHAR(30),
  role_id INT NOT NULL REFERENCES roles(role_id),
  invite_token UUID NOT NULL DEFAULT gen_random_uuid(),
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  expires_at TIMESTAMPTZ NOT NULL,
  accepted_by_user_id BIGINT REFERENCES app_users(user_id),
  accepted_at TIMESTAMPTZ,
  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT ck_business_invitations_status CHECK (status IN ('PENDING','ACCEPTED','EXPIRED','CANCELLED'))
);

CREATE UNIQUE INDEX ux_business_invitations_token ON business_invitations(invite_token);
CREATE INDEX ix_business_invitations_business ON business_invitations(business_id, status);

CREATE TRIGGER trg_business_invitations_updated_at
BEFORE UPDATE ON business_invitations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE user_devices (
  user_device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES app_users(user_id) ON DELETE CASCADE,
  business_id BIGINT REFERENCES businesses(business_id) ON DELETE CASCADE,
  platform VARCHAR(30) NOT NULL DEFAULT 'ANDROID',
  device_name VARCHAR(200),
  device_id VARCHAR(200),
  fcm_token TEXT,
  app_version VARCHAR(50),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_seen_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX ix_user_devices_user_id ON user_devices(user_id);
CREATE INDEX ix_user_devices_business_id ON user_devices(business_id);

CREATE TRIGGER trg_user_devices_updated_at
BEFORE UPDATE ON user_devices
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 2. Subscription management
-- =========================================================

CREATE TABLE subscription_plans (
  plan_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_name VARCHAR(100) NOT NULL,
  plan_code VARCHAR(50) NOT NULL UNIQUE,

  monthly_price NUMERIC(18,2) NOT NULL DEFAULT 0,
  currency_code VARCHAR(10) NOT NULL DEFAULT 'PKR',

  max_businesses INT,
  max_users INT,
  max_customers INT,
  max_products INT,
  max_invoices_per_month INT,

  has_inventory BOOLEAN NOT NULL DEFAULT TRUE,
  has_quotation BOOLEAN NOT NULL DEFAULT TRUE,
  has_reports BOOLEAN NOT NULL DEFAULT TRUE,
  has_whatsapp_sharing BOOLEAN NOT NULL DEFAULT TRUE,
  has_multi_user BOOLEAN NOT NULL DEFAULT FALSE,

  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE TRIGGER trg_subscription_plans_updated_at
BEFORE UPDATE ON subscription_plans
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE business_subscriptions (
  business_subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  plan_id INT NOT NULL REFERENCES subscription_plans(plan_id),

  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  subscription_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  is_trial BOOLEAN NOT NULL DEFAULT FALSE,
  auto_renew BOOLEAN NOT NULL DEFAULT FALSE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT ck_business_subscriptions_status CHECK (subscription_status IN ('ACTIVE','EXPIRED','TRIAL','CANCELLED','BLOCKED')),
  CONSTRAINT ck_business_subscriptions_dates CHECK (end_date >= start_date)
);

CREATE INDEX ix_business_subscriptions_business_id ON business_subscriptions(business_id);
CREATE INDEX ix_business_subscriptions_status_end_date ON business_subscriptions(subscription_status, end_date);

CREATE TRIGGER trg_business_subscriptions_updated_at
BEFORE UPDATE ON business_subscriptions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE subscription_payments (
  subscription_payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_subscription_id BIGINT NOT NULL REFERENCES business_subscriptions(business_subscription_id) ON DELETE CASCADE,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,

  amount NUMERIC(18,2) NOT NULL,
  currency_code VARCHAR(10) NOT NULL DEFAULT 'PKR',
  payment_method VARCHAR(50),
  transaction_reference VARCHAR(150),
  payment_screenshot_url TEXT,

  payment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  paid_at TIMESTAMPTZ,
  approved_by BIGINT REFERENCES app_users(user_id),
  approved_at TIMESTAMPTZ,
  reject_reason TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT ck_subscription_payments_status CHECK (payment_status IN ('PENDING','APPROVED','REJECTED'))
);

CREATE INDEX ix_subscription_payments_business_id ON subscription_payments(business_id);
CREATE INDEX ix_subscription_payments_status ON subscription_payments(payment_status);

CREATE TRIGGER trg_subscription_payments_updated_at
BEFORE UPDATE ON subscription_payments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 3. Business settings and document sequences
-- =========================================================

CREATE TABLE business_settings (
  business_setting_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL UNIQUE REFERENCES businesses(business_id) ON DELETE CASCADE,

  invoice_prefix VARCHAR(20) NOT NULL DEFAULT 'INV',
  quotation_prefix VARCHAR(20) NOT NULL DEFAULT 'QT',
  purchase_prefix VARCHAR(20) NOT NULL DEFAULT 'PUR',

  show_logo_on_invoice BOOLEAN NOT NULL DEFAULT TRUE,
  show_tax_on_invoice BOOLEAN NOT NULL DEFAULT FALSE,
  default_tax_percent NUMERIC(9,2) NOT NULL DEFAULT 0,

  invoice_terms TEXT,
  invoice_footer_text TEXT,

  allow_negative_stock BOOLEAN NOT NULL DEFAULT FALSE,
  low_stock_alert BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE TRIGGER trg_business_settings_updated_at
BEFORE UPDATE ON business_settings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE document_sequences (
  document_sequence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  document_type VARCHAR(30) NOT NULL,
  prefix VARCHAR(20) NOT NULL,
  next_number BIGINT NOT NULL DEFAULT 1,
  padding_length INT NOT NULL DEFAULT 5,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  UNIQUE(business_id, document_type),
  CONSTRAINT ck_document_sequences_type CHECK (document_type IN ('SALE_INVOICE','QUOTATION','PURCHASE_BILL')),
  CONSTRAINT ck_document_sequences_next_number CHECK (next_number > 0),
  CONSTRAINT ck_document_sequences_padding CHECK (padding_length BETWEEN 1 AND 12)
);

CREATE TRIGGER trg_document_sequences_updated_at
BEFORE UPDATE ON document_sequences
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION next_document_no(p_business_id BIGINT, p_document_type VARCHAR)
RETURNS VARCHAR AS $$
DECLARE
  v_prefix VARCHAR(20);
  v_next_number BIGINT;
  v_padding INT;
BEGIN
  UPDATE document_sequences
  SET next_number = next_number + 1,
      updated_at = NOW()
  WHERE business_id = p_business_id
    AND document_type = p_document_type
  RETURNING prefix, next_number - 1, padding_length
  INTO v_prefix, v_next_number, v_padding;

  IF v_next_number IS NULL THEN
    RAISE EXCEPTION 'Document sequence not found for business_id=% document_type=%', p_business_id, p_document_type;
  END IF;

  RETURN v_prefix || '-' || LPAD(v_next_number::TEXT, v_padding, '0');
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- 4. Customers and suppliers
-- =========================================================

CREATE TABLE customers (
  customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,

  customer_name VARCHAR(200) NOT NULL,
  phone_number VARCHAR(30),
  whatsapp_number VARCHAR(30),
  email VARCHAR(150),
  address TEXT,
  city VARCHAR(100),
  customer_type VARCHAR(50) NOT NULL DEFAULT 'Retail',

  opening_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
  current_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
  credit_limit NUMERIC(18,2),
  notes TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_customers_public_id ON customers(public_id);
CREATE INDEX ix_customers_business_id ON customers(business_id);
CREATE INDEX ix_customers_business_phone ON customers(business_id, phone_number);
CREATE INDEX ix_customers_business_name ON customers(business_id, LOWER(customer_name));

CREATE TRIGGER trg_customers_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE suppliers (
  supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,

  supplier_name VARCHAR(200) NOT NULL,
  phone_number VARCHAR(30),
  whatsapp_number VARCHAR(30),
  email VARCHAR(150),
  address TEXT,
  city VARCHAR(100),

  opening_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
  current_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
  notes TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_suppliers_public_id ON suppliers(public_id);
CREATE INDEX ix_suppliers_business_id ON suppliers(business_id);
CREATE INDEX ix_suppliers_business_phone ON suppliers(business_id, phone_number);

CREATE TRIGGER trg_suppliers_updated_at
BEFORE UPDATE ON suppliers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 5. Products and inventory
-- =========================================================

CREATE TABLE units (
  unit_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_name VARCHAR(50) NOT NULL,
  unit_code VARCHAR(20) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE product_categories (
  product_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  category_name VARCHAR(150) NOT NULL,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX ix_product_categories_business_id ON product_categories(business_id);
CREATE UNIQUE INDEX ux_product_categories_business_name ON product_categories(business_id, LOWER(category_name)) WHERE is_deleted = FALSE;

CREATE TRIGGER trg_product_categories_updated_at
BEFORE UPDATE ON product_categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE products (
  product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  product_category_id BIGINT REFERENCES product_categories(product_category_id),
  unit_id INT NOT NULL REFERENCES units(unit_id),

  product_name VARCHAR(200) NOT NULL,
  sku VARCHAR(100),
  barcode VARCHAR(100),
  product_type VARCHAR(30) NOT NULL DEFAULT 'PRODUCT',

  purchase_price NUMERIC(18,2) NOT NULL DEFAULT 0,
  sale_price NUMERIC(18,2) NOT NULL DEFAULT 0,
  tax_percent NUMERIC(9,2) NOT NULL DEFAULT 0,

  opening_stock NUMERIC(18,3) NOT NULL DEFAULT 0,
  current_stock NUMERIC(18,3) NOT NULL DEFAULT 0,
  low_stock_qty NUMERIC(18,3),

  product_image_url TEXT,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

  CONSTRAINT ck_products_type CHECK (product_type IN ('PRODUCT','SERVICE'))
);

CREATE UNIQUE INDEX ux_products_public_id ON products(public_id);
CREATE INDEX ix_products_business_id ON products(business_id);
CREATE INDEX ix_products_business_name ON products(business_id, LOWER(product_name));
CREATE INDEX ix_products_business_sku ON products(business_id, sku) WHERE sku IS NOT NULL AND is_deleted = FALSE;
CREATE INDEX ix_products_business_barcode ON products(business_id, barcode) WHERE barcode IS NOT NULL AND is_deleted = FALSE;

CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE warehouses (
  warehouse_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  warehouse_name VARCHAR(150) NOT NULL,
  address TEXT,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX ix_warehouses_business_id ON warehouses(business_id);
CREATE UNIQUE INDEX ux_warehouses_default_per_business ON warehouses(business_id) WHERE is_default = TRUE AND is_deleted = FALSE;

CREATE TRIGGER trg_warehouses_updated_at
BEFORE UPDATE ON warehouses
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE product_stock (
  product_stock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  warehouse_id BIGINT NOT NULL REFERENCES warehouses(warehouse_id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,
  current_qty NUMERIC(18,3) NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ,
  UNIQUE(business_id, warehouse_id, product_id)
);

CREATE INDEX ix_product_stock_product_id ON product_stock(product_id);

CREATE TRIGGER trg_product_stock_updated_at
BEFORE UPDATE ON product_stock
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE inventory_transactions (
  inventory_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  warehouse_id BIGINT NOT NULL REFERENCES warehouses(warehouse_id),
  product_id BIGINT NOT NULL REFERENCES products(product_id),

  transaction_type VARCHAR(50) NOT NULL,
  reference_type VARCHAR(50),
  reference_id BIGINT,

  qty_in NUMERIC(18,3) NOT NULL DEFAULT 0,
  qty_out NUMERIC(18,3) NOT NULL DEFAULT 0,
  unit_cost NUMERIC(18,2),
  notes TEXT,
  transaction_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT ck_inventory_transactions_type CHECK (transaction_type IN ('OPENING','SALE','SALE_RETURN','PURCHASE','PURCHASE_RETURN','ADJUSTMENT_IN','ADJUSTMENT_OUT','DAMAGE')),
  CONSTRAINT ck_inventory_transactions_qty CHECK (qty_in >= 0 AND qty_out >= 0 AND (qty_in > 0 OR qty_out > 0))
);

CREATE INDEX ix_inventory_transactions_business_product ON inventory_transactions(business_id, product_id);
CREATE INDEX ix_inventory_transactions_reference ON inventory_transactions(reference_type, reference_id);
CREATE INDEX ix_inventory_transactions_date ON inventory_transactions(business_id, transaction_date);

-- =========================================================
-- 6. Sales invoices, payments, and customer ledger
-- =========================================================

CREATE TABLE sales_invoices (
  sales_invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  customer_id BIGINT REFERENCES customers(customer_id),

  invoice_no VARCHAR(50) NOT NULL,
  invoice_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  customer_name_snapshot VARCHAR(200),
  customer_phone_snapshot VARCHAR(30),
  customer_address_snapshot TEXT,

  sub_total NUMERIC(18,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  grand_total NUMERIC(18,2) NOT NULL DEFAULT 0,
  paid_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  balance_amount NUMERIC(18,2) NOT NULL DEFAULT 0,

  payment_status VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
  invoice_status VARCHAR(30) NOT NULL DEFAULT 'POSTED',

  notes TEXT,
  terms TEXT,
  pdf_url TEXT,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

  CONSTRAINT ck_sales_invoices_payment_status CHECK (payment_status IN ('PAID','PARTIAL','UNPAID')),
  CONSTRAINT ck_sales_invoices_status CHECK (invoice_status IN ('DRAFT','POSTED','CANCELLED')),
  CONSTRAINT ck_sales_invoices_amounts CHECK (sub_total >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND grand_total >= 0 AND paid_amount >= 0 AND balance_amount >= 0)
);

CREATE UNIQUE INDEX ux_sales_invoices_public_id ON sales_invoices(public_id);
CREATE UNIQUE INDEX ux_sales_invoices_business_invoice_no ON sales_invoices(business_id, invoice_no) WHERE is_deleted = FALSE;
CREATE INDEX ix_sales_invoices_business_date ON sales_invoices(business_id, invoice_date);
CREATE INDEX ix_sales_invoices_customer ON sales_invoices(business_id, customer_id);
CREATE INDEX ix_sales_invoices_payment_status ON sales_invoices(business_id, payment_status);

CREATE TRIGGER trg_sales_invoices_updated_at
BEFORE UPDATE ON sales_invoices
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE sales_invoice_items (
  sales_invoice_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sales_invoice_id BIGINT NOT NULL REFERENCES sales_invoices(sales_invoice_id) ON DELETE CASCADE,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(product_id),

  item_name_snapshot VARCHAR(200) NOT NULL,
  sku_snapshot VARCHAR(100),
  qty NUMERIC(18,3) NOT NULL DEFAULT 1,
  unit_price NUMERIC(18,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  tax_percent NUMERIC(9,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  line_total NUMERIC(18,2) NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT ck_sales_invoice_items_amounts CHECK (qty > 0 AND unit_price >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND line_total >= 0)
);

CREATE INDEX ix_sales_invoice_items_invoice ON sales_invoice_items(sales_invoice_id);
CREATE INDEX ix_sales_invoice_items_product ON sales_invoice_items(business_id, product_id);

CREATE TABLE payments_received (
  payment_received_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  customer_id BIGINT NOT NULL REFERENCES customers(customer_id),

  payment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  amount NUMERIC(18,2) NOT NULL,
  payment_method VARCHAR(50) NOT NULL DEFAULT 'Cash',
  reference_no VARCHAR(150),
  description TEXT,
  attachment_url TEXT,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

  CONSTRAINT ck_payments_received_amount CHECK (amount > 0)
);

CREATE UNIQUE INDEX ux_payments_received_public_id ON payments_received(public_id);
CREATE INDEX ix_payments_received_business_customer ON payments_received(business_id, customer_id);
CREATE INDEX ix_payments_received_date ON payments_received(business_id, payment_date);

CREATE TRIGGER trg_payments_received_updated_at
BEFORE UPDATE ON payments_received
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE payment_allocations (
  payment_allocation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  payment_received_id BIGINT NOT NULL REFERENCES payments_received(payment_received_id) ON DELETE CASCADE,
  sales_invoice_id BIGINT NOT NULL REFERENCES sales_invoices(sales_invoice_id) ON DELETE CASCADE,
  allocated_amount NUMERIC(18,2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_payment_allocations_amount CHECK (allocated_amount > 0)
);

CREATE INDEX ix_payment_allocations_payment ON payment_allocations(payment_received_id);
CREATE INDEX ix_payment_allocations_invoice ON payment_allocations(sales_invoice_id);

CREATE TABLE customer_ledger (
  customer_ledger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  customer_id BIGINT NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,

  ledger_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  entry_type VARCHAR(50) NOT NULL,
  reference_type VARCHAR(50),
  reference_id BIGINT,

  debit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  credit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  balance_after NUMERIC(18,2) NOT NULL DEFAULT 0,
  description TEXT,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT ck_customer_ledger_entry_type CHECK (entry_type IN ('OPENING','SALE','PAYMENT','SALE_RETURN','ADJUSTMENT')),
  CONSTRAINT ck_customer_ledger_amounts CHECK (debit_amount >= 0 AND credit_amount >= 0 AND (debit_amount > 0 OR credit_amount > 0))
);

CREATE INDEX ix_customer_ledger_customer_date ON customer_ledger(business_id, customer_id, ledger_date);
CREATE INDEX ix_customer_ledger_reference ON customer_ledger(reference_type, reference_id);

-- =========================================================
-- 7. Quotations
-- =========================================================

CREATE TABLE quotations (
  quotation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  customer_id BIGINT REFERENCES customers(customer_id),

  quotation_no VARCHAR(50) NOT NULL,
  quotation_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  valid_until DATE,

  customer_name_snapshot VARCHAR(200),
  customer_phone_snapshot VARCHAR(30),
  customer_address_snapshot TEXT,

  sub_total NUMERIC(18,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  grand_total NUMERIC(18,2) NOT NULL DEFAULT 0,

  quotation_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  converted_sales_invoice_id BIGINT REFERENCES sales_invoices(sales_invoice_id),

  notes TEXT,
  terms TEXT,
  pdf_url TEXT,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

  CONSTRAINT ck_quotations_status CHECK (quotation_status IN ('PENDING','ACCEPTED','REJECTED','EXPIRED','CONVERTED'))
);

CREATE UNIQUE INDEX ux_quotations_public_id ON quotations(public_id);
CREATE UNIQUE INDEX ux_quotations_business_quotation_no ON quotations(business_id, quotation_no) WHERE is_deleted = FALSE;
CREATE INDEX ix_quotations_business_date ON quotations(business_id, quotation_date);

CREATE TRIGGER trg_quotations_updated_at
BEFORE UPDATE ON quotations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE quotation_items (
  quotation_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quotation_id BIGINT NOT NULL REFERENCES quotations(quotation_id) ON DELETE CASCADE,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(product_id),

  item_name_snapshot VARCHAR(200) NOT NULL,
  sku_snapshot VARCHAR(100),
  qty NUMERIC(18,3) NOT NULL DEFAULT 1,
  unit_price NUMERIC(18,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  tax_percent NUMERIC(9,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  line_total NUMERIC(18,2) NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT ck_quotation_items_amounts CHECK (qty > 0 AND unit_price >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND line_total >= 0)
);

CREATE INDEX ix_quotation_items_quotation ON quotation_items(quotation_id);

-- =========================================================
-- 8. Purchases and supplier ledger
-- =========================================================

CREATE TABLE purchase_bills (
  purchase_bill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  supplier_id BIGINT REFERENCES suppliers(supplier_id),

  purchase_no VARCHAR(50) NOT NULL,
  purchase_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  supplier_name_snapshot VARCHAR(200),
  supplier_phone_snapshot VARCHAR(30),

  sub_total NUMERIC(18,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  grand_total NUMERIC(18,2) NOT NULL DEFAULT 0,
  paid_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  balance_amount NUMERIC(18,2) NOT NULL DEFAULT 0,

  payment_status VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
  bill_status VARCHAR(30) NOT NULL DEFAULT 'POSTED',
  notes TEXT,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

  CONSTRAINT ck_purchase_bills_payment_status CHECK (payment_status IN ('PAID','PARTIAL','UNPAID')),
  CONSTRAINT ck_purchase_bills_status CHECK (bill_status IN ('DRAFT','POSTED','CANCELLED'))
);

CREATE UNIQUE INDEX ux_purchase_bills_public_id ON purchase_bills(public_id);
CREATE UNIQUE INDEX ux_purchase_bills_business_purchase_no ON purchase_bills(business_id, purchase_no) WHERE is_deleted = FALSE;
CREATE INDEX ix_purchase_bills_business_date ON purchase_bills(business_id, purchase_date);

CREATE TRIGGER trg_purchase_bills_updated_at
BEFORE UPDATE ON purchase_bills
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE purchase_bill_items (
  purchase_bill_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_bill_id BIGINT NOT NULL REFERENCES purchase_bills(purchase_bill_id) ON DELETE CASCADE,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(product_id),

  item_name_snapshot VARCHAR(200) NOT NULL,
  qty NUMERIC(18,3) NOT NULL DEFAULT 1,
  unit_cost NUMERIC(18,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  tax_percent NUMERIC(9,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  line_total NUMERIC(18,2) NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT ck_purchase_bill_items_amounts CHECK (qty > 0 AND unit_cost >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND line_total >= 0)
);

CREATE INDEX ix_purchase_bill_items_bill ON purchase_bill_items(purchase_bill_id);
CREATE INDEX ix_purchase_bill_items_product ON purchase_bill_items(business_id, product_id);

CREATE TABLE supplier_payments (
  supplier_payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  supplier_id BIGINT NOT NULL REFERENCES suppliers(supplier_id),

  payment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  amount NUMERIC(18,2) NOT NULL,
  payment_method VARCHAR(50) NOT NULL DEFAULT 'Cash',
  reference_no VARCHAR(150),
  description TEXT,
  attachment_url TEXT,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

  CONSTRAINT ck_supplier_payments_amount CHECK (amount > 0)
);

CREATE UNIQUE INDEX ux_supplier_payments_public_id ON supplier_payments(public_id);
CREATE INDEX ix_supplier_payments_business_supplier ON supplier_payments(business_id, supplier_id);
CREATE INDEX ix_supplier_payments_date ON supplier_payments(business_id, payment_date);

CREATE TRIGGER trg_supplier_payments_updated_at
BEFORE UPDATE ON supplier_payments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE supplier_ledger (
  supplier_ledger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  supplier_id BIGINT NOT NULL REFERENCES suppliers(supplier_id) ON DELETE CASCADE,

  ledger_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  entry_type VARCHAR(50) NOT NULL,
  reference_type VARCHAR(50),
  reference_id BIGINT,

  debit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  credit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  balance_after NUMERIC(18,2) NOT NULL DEFAULT 0,
  description TEXT,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT ck_supplier_ledger_entry_type CHECK (entry_type IN ('OPENING','PURCHASE','PAYMENT','PURCHASE_RETURN','ADJUSTMENT')),
  CONSTRAINT ck_supplier_ledger_amounts CHECK (debit_amount >= 0 AND credit_amount >= 0 AND (debit_amount > 0 OR credit_amount > 0))
);

CREATE INDEX ix_supplier_ledger_supplier_date ON supplier_ledger(business_id, supplier_id, ledger_date);
CREATE INDEX ix_supplier_ledger_reference ON supplier_ledger(reference_type, reference_id);

-- =========================================================
-- 9. Expenses
-- =========================================================

CREATE TABLE expense_categories (
  expense_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  category_name VARCHAR(150) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_expense_categories_business_name ON expense_categories(business_id, LOWER(category_name)) WHERE is_deleted = FALSE;

CREATE TRIGGER trg_expense_categories_updated_at
BEFORE UPDATE ON expense_categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE expenses (
  expense_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  expense_category_id BIGINT REFERENCES expense_categories(expense_category_id),

  expense_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  title VARCHAR(200) NOT NULL,
  amount NUMERIC(18,2) NOT NULL,
  payment_method VARCHAR(50),
  description TEXT,
  attachment_url TEXT,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

  CONSTRAINT ck_expenses_amount CHECK (amount > 0)
);

CREATE UNIQUE INDEX ux_expenses_public_id ON expenses(public_id);
CREATE INDEX ix_expenses_business_date ON expenses(business_id, expense_date);

CREATE TRIGGER trg_expenses_updated_at
BEFORE UPDATE ON expenses
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 10. Reminders, notifications, attachments, WhatsApp logs
-- =========================================================

CREATE TABLE reminders (
  reminder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  customer_id BIGINT REFERENCES customers(customer_id),
  supplier_id BIGINT REFERENCES suppliers(supplier_id),

  reminder_type VARCHAR(50) NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  reminder_datetime TIMESTAMPTZ NOT NULL,
  reminder_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  reference_type VARCHAR(50),
  reference_id BIGINT,

  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

  CONSTRAINT ck_reminders_type CHECK (reminder_type IN ('PAYMENT_DUE','QUOTATION_FOLLOWUP','CHEQUE','LOW_STOCK','GENERAL')),
  CONSTRAINT ck_reminders_status CHECK (reminder_status IN ('PENDING','DONE','SNOOZED','CANCELLED'))
);

CREATE UNIQUE INDEX ux_reminders_public_id ON reminders(public_id);
CREATE INDEX ix_reminders_business_date_status ON reminders(business_id, reminder_datetime, reminder_status);
CREATE INDEX ix_reminders_reference ON reminders(reference_type, reference_id);

CREATE TRIGGER trg_reminders_updated_at
BEFORE UPDATE ON reminders
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE whatsapp_share_logs (
  whatsapp_share_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,

  document_type VARCHAR(50) NOT NULL,
  document_id BIGINT NOT NULL,
  phone_number VARCHAR(30) NOT NULL,
  message_text TEXT,
  file_url TEXT,
  share_status VARCHAR(30) NOT NULL DEFAULT 'OPENED',

  shared_by BIGINT REFERENCES app_users(user_id),
  shared_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT ck_whatsapp_share_logs_status CHECK (share_status IN ('OPENED','SENT_MANUAL','FAILED'))
);

CREATE INDEX ix_whatsapp_share_logs_business_document ON whatsapp_share_logs(business_id, document_type, document_id);

CREATE TABLE notifications (
  notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT REFERENCES businesses(business_id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES app_users(user_id) ON DELETE CASCADE,

  title VARCHAR(200) NOT NULL,
  message TEXT NOT NULL,
  notification_type VARCHAR(50),
  reference_type VARCHAR(50),
  reference_id BIGINT,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_notifications_user_read ON notifications(user_id, is_read, created_at);
CREATE INDEX ix_notifications_business ON notifications(business_id, created_at);

CREATE TABLE attachments (
  attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  reference_type VARCHAR(50) NOT NULL,
  reference_id BIGINT NOT NULL,

  file_name VARCHAR(255) NOT NULL,
  file_url TEXT NOT NULL,
  file_type VARCHAR(100),
  file_size_bytes BIGINT,

  uploaded_by BIGINT REFERENCES app_users(user_id),
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_attachments_reference ON attachments(business_id, reference_type, reference_id);

CREATE TABLE audit_logs (
  audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT REFERENCES businesses(business_id) ON DELETE SET NULL,
  user_id BIGINT REFERENCES app_users(user_id) ON DELETE SET NULL,

  action_name VARCHAR(100) NOT NULL,
  entity_name VARCHAR(100),
  entity_id BIGINT,
  old_values JSONB,
  new_values JSONB,
  ip_address VARCHAR(50),
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_audit_logs_business_date ON audit_logs(business_id, created_at);
CREATE INDEX ix_audit_logs_user_date ON audit_logs(user_id, created_at);
CREATE INDEX ix_audit_logs_entity ON audit_logs(entity_name, entity_id);

-- =========================================================
-- 11. Useful report views
-- =========================================================

CREATE OR REPLACE VIEW vw_customer_balances AS
SELECT
  c.business_id,
  c.customer_id,
  c.public_id,
  c.customer_name,
  c.phone_number,
  c.whatsapp_number,
  c.current_balance,
  c.credit_limit
FROM customers c
WHERE c.is_deleted = FALSE;

CREATE OR REPLACE VIEW vw_sales_summary_daily AS
SELECT
  business_id,
  invoice_date::DATE AS sale_date,
  COUNT(*) AS total_invoices,
  COALESCE(SUM(grand_total), 0) AS total_sales,
  COALESCE(SUM(paid_amount), 0) AS total_paid,
  COALESCE(SUM(balance_amount), 0) AS total_balance
FROM sales_invoices
WHERE is_deleted = FALSE
  AND invoice_status <> 'CANCELLED'
GROUP BY business_id, invoice_date::DATE;

CREATE OR REPLACE VIEW vw_low_stock_products AS
SELECT
  p.business_id,
  p.product_id,
  p.public_id,
  p.product_name,
  p.sku,
  p.current_stock,
  p.low_stock_qty
FROM products p
WHERE p.is_deleted = FALSE
  AND p.product_type = 'PRODUCT'
  AND p.low_stock_qty IS NOT NULL
  AND p.current_stock <= p.low_stock_qty;

CREATE OR REPLACE VIEW vw_unpaid_sales_invoices AS
SELECT
  si.business_id,
  si.sales_invoice_id,
  si.public_id,
  si.customer_id,
  si.invoice_no,
  si.invoice_date,
  COALESCE(c.customer_name, si.customer_name_snapshot) AS customer_name,
  si.grand_total,
  si.paid_amount,
  si.balance_amount,
  si.payment_status
FROM sales_invoices si
LEFT JOIN customers c ON c.customer_id = si.customer_id
WHERE si.is_deleted = FALSE
  AND si.invoice_status <> 'CANCELLED'
  AND si.balance_amount > 0;
