-- Admin portal feature support: WhatsApp API settings per business

CREATE TABLE IF NOT EXISTS business_whatsapp_settings (
  business_whatsapp_setting_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  provider VARCHAR(50) NOT NULL DEFAULT 'custom',
  api_url TEXT,
  api_key TEXT,
  sender_phone VARCHAR(50),
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  UNIQUE(business_id)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_business_whatsapp_settings_updated_at'
  ) THEN
    CREATE TRIGGER trg_business_whatsapp_settings_updated_at
    BEFORE UPDATE ON business_whatsapp_settings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_business_whatsapp_settings_business_id ON business_whatsapp_settings(business_id);
