-- Smart Khata complete business suite support tables
-- Adds Phase 1/2/3/4 ready modules without breaking existing data.


-- Add public ids to older master tables that were created before the full-suite modules.
ALTER TABLE product_categories ADD COLUMN IF NOT EXISTS public_id UUID NOT NULL DEFAULT gen_random_uuid();
CREATE UNIQUE INDEX IF NOT EXISTS ux_product_categories_public_id ON product_categories(public_id);
ALTER TABLE expense_categories ADD COLUMN IF NOT EXISTS public_id UUID NOT NULL DEFAULT gen_random_uuid();
CREATE UNIQUE INDEX IF NOT EXISTS ux_expense_categories_public_id ON expense_categories(public_id);

CREATE TABLE IF NOT EXISTS branches (
  branch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  branch_name VARCHAR(150) NOT NULL,
  phone_number VARCHAR(30),
  address TEXT,
  city VARCHAR(100),
  is_main BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_branches_public_id ON branches(public_id);
CREATE INDEX IF NOT EXISTS ix_branches_business_id ON branches(business_id);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_branches_updated_at') THEN
  CREATE TRIGGER trg_branches_updated_at BEFORE UPDATE ON branches FOR EACH ROW EXECUTE FUNCTION set_updated_at();
END IF; END $$;

CREATE TABLE IF NOT EXISTS financial_accounts (
  financial_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  account_name VARCHAR(150) NOT NULL,
  account_type VARCHAR(50) NOT NULL DEFAULT 'CASH',
  account_number VARCHAR(100),
  opening_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
  current_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT ck_financial_accounts_type CHECK (account_type IN ('CASH','BANK','EASYPAISA','JAZZCASH','RAAST','CARD','WALLET','OTHER'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_financial_accounts_public_id ON financial_accounts(public_id);
CREATE INDEX IF NOT EXISTS ix_financial_accounts_business_id ON financial_accounts(business_id);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_financial_accounts_updated_at') THEN
  CREATE TRIGGER trg_financial_accounts_updated_at BEFORE UPDATE ON financial_accounts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
END IF; END $$;

CREATE TABLE IF NOT EXISTS cash_book_entries (
  cash_book_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  financial_account_id BIGINT REFERENCES financial_accounts(financial_account_id),
  entry_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  entry_type VARCHAR(30) NOT NULL,
  amount NUMERIC(18,2) NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  reference_type VARCHAR(50),
  reference_id BIGINT,
  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT ck_cash_book_entry_type CHECK (entry_type IN ('CASH_IN','CASH_OUT','TRANSFER_IN','TRANSFER_OUT','OPENING')),
  CONSTRAINT ck_cash_book_amount CHECK (amount > 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_cash_book_entries_public_id ON cash_book_entries(public_id);
CREATE INDEX IF NOT EXISTS ix_cash_book_entries_business_date ON cash_book_entries(business_id, entry_date);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_cash_book_entries_updated_at') THEN
  CREATE TRIGGER trg_cash_book_entries_updated_at BEFORE UPDATE ON cash_book_entries FOR EACH ROW EXECUTE FUNCTION set_updated_at();
END IF; END $$;

CREATE TABLE IF NOT EXISTS cheque_records (
  cheque_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  party_type VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER',
  customer_id BIGINT REFERENCES customers(customer_id),
  supplier_id BIGINT REFERENCES suppliers(supplier_id),
  cheque_no VARCHAR(100),
  bank_name VARCHAR(150),
  amount NUMERIC(18,2) NOT NULL,
  cheque_date DATE,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  notes TEXT,
  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT ck_cheque_party_type CHECK (party_type IN ('CUSTOMER','SUPPLIER','OTHER')),
  CONSTRAINT ck_cheque_status CHECK (status IN ('PENDING','CLEARED','BOUNCED','CANCELLED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_cheque_records_public_id ON cheque_records(public_id);
CREATE INDEX IF NOT EXISTS ix_cheque_records_business_status ON cheque_records(business_id, status);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_cheque_records_updated_at') THEN
  CREATE TRIGGER trg_cheque_records_updated_at BEFORE UPDATE ON cheque_records FOR EACH ROW EXECUTE FUNCTION set_updated_at();
END IF; END $$;

CREATE TABLE IF NOT EXISTS staff_members (
  staff_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES app_users(user_id),
  full_name VARCHAR(150) NOT NULL,
  phone_number VARCHAR(30),
  role_title VARCHAR(100),
  salary_type VARCHAR(30) NOT NULL DEFAULT 'MONTHLY',
  salary_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  joining_date DATE,
  cnic VARCHAR(50),
  address TEXT,
  can_login BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT ck_staff_salary_type CHECK (salary_type IN ('MONTHLY','DAILY','HOURLY'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_staff_members_public_id ON staff_members(public_id);
CREATE INDEX IF NOT EXISTS ix_staff_members_business_id ON staff_members(business_id);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_staff_members_updated_at') THEN
  CREATE TRIGGER trg_staff_members_updated_at BEFORE UPDATE ON staff_members FOR EACH ROW EXECUTE FUNCTION set_updated_at();
END IF; END $$;

CREATE TABLE IF NOT EXISTS attendance_records (
  attendance_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  staff_member_id BIGINT NOT NULL REFERENCES staff_members(staff_member_id) ON DELETE CASCADE,
  attendance_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR(30) NOT NULL DEFAULT 'PRESENT',
  check_in_time TIME,
  check_out_time TIME,
  overtime_hours NUMERIC(9,2) NOT NULL DEFAULT 0,
  notes TEXT,
  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE(business_id, staff_member_id, attendance_date),
  CONSTRAINT ck_attendance_status CHECK (status IN ('PRESENT','ABSENT','HALF_DAY','LEAVE','LATE'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_attendance_records_public_id ON attendance_records(public_id);
CREATE INDEX IF NOT EXISTS ix_attendance_records_business_date ON attendance_records(business_id, attendance_date);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_attendance_records_updated_at') THEN
  CREATE TRIGGER trg_attendance_records_updated_at BEFORE UPDATE ON attendance_records FOR EACH ROW EXECUTE FUNCTION set_updated_at();
END IF; END $$;

CREATE TABLE IF NOT EXISTS payroll_runs (
  payroll_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  payroll_month DATE NOT NULL,
  title VARCHAR(150),
  gross_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  deduction_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  net_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  paid_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT ck_payroll_run_status CHECK (status IN ('DRAFT','POSTED','PAID','CANCELLED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_payroll_runs_public_id ON payroll_runs(public_id);
CREATE INDEX IF NOT EXISTS ix_payroll_runs_business_month ON payroll_runs(business_id, payroll_month);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_payroll_runs_updated_at') THEN
  CREATE TRIGGER trg_payroll_runs_updated_at BEFORE UPDATE ON payroll_runs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
END IF; END $$;

CREATE TABLE IF NOT EXISTS payroll_items (
  payroll_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_run_id BIGINT NOT NULL REFERENCES payroll_runs(payroll_run_id) ON DELETE CASCADE,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  staff_member_id BIGINT NOT NULL REFERENCES staff_members(staff_member_id),
  basic_salary NUMERIC(18,2) NOT NULL DEFAULT 0,
  overtime_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  bonus_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  advance_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  deduction_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  net_payable NUMERIC(18,2) NOT NULL DEFAULT 0,
  paid_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_payroll_item_status CHECK (status IN ('UNPAID','PARTIAL','PAID'))
);
CREATE INDEX IF NOT EXISTS ix_payroll_items_run ON payroll_items(payroll_run_id);

CREATE TABLE IF NOT EXISTS support_tickets (
  support_ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT REFERENCES businesses(business_id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES app_users(user_id) ON DELETE SET NULL,
  subject VARCHAR(200) NOT NULL,
  message TEXT,
  status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
  priority VARCHAR(30) NOT NULL DEFAULT 'NORMAL',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT ck_support_ticket_status CHECK (status IN ('OPEN','IN_PROGRESS','RESOLVED','CLOSED')),
  CONSTRAINT ck_support_ticket_priority CHECK (priority IN ('LOW','NORMAL','HIGH','URGENT'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_support_tickets_public_id ON support_tickets(public_id);
CREATE INDEX IF NOT EXISTS ix_support_tickets_business_status ON support_tickets(business_id, status);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_support_tickets_updated_at') THEN
  CREATE TRIGGER trg_support_tickets_updated_at BEFORE UPDATE ON support_tickets FOR EACH ROW EXECUTE FUNCTION set_updated_at();
END IF; END $$;

CREATE TABLE IF NOT EXISTS backup_export_requests (
  backup_export_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  export_type VARCHAR(50) NOT NULL DEFAULT 'ALL',
  status VARCHAR(30) NOT NULL DEFAULT 'REQUESTED',
  file_url TEXT,
  requested_by BIGINT REFERENCES app_users(user_id),
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  notes TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_backup_export_requests_public_id ON backup_export_requests(public_id);
CREATE INDEX IF NOT EXISTS ix_backup_export_requests_business_status ON backup_export_requests(business_id, status);

-- Ensure each business gets one default branch and one default cash account.
INSERT INTO branches(business_id, branch_name, is_main, is_active)
SELECT b.business_id, 'Main Branch', TRUE, TRUE
FROM businesses b
WHERE b.is_deleted=FALSE AND NOT EXISTS (SELECT 1 FROM branches br WHERE br.business_id=b.business_id AND br.is_deleted=FALSE);

INSERT INTO financial_accounts(business_id, account_name, account_type, opening_balance, current_balance, is_default, is_active)
SELECT b.business_id, 'Cash', 'CASH', 0, 0, TRUE, TRUE
FROM businesses b
WHERE b.is_deleted=FALSE AND NOT EXISTS (SELECT 1 FROM financial_accounts fa WHERE fa.business_id=b.business_id AND fa.is_deleted=FALSE);
