-- Smart Khata mobile app enhancements: WhatsApp OTP, POS helper fields, owner shop and orders
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS whatsapp_otp_codes (
  otp_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number VARCHAR(30) NOT NULL,
  otp_hash TEXT NOT NULL,
  purpose VARCHAR(30) NOT NULL DEFAULT 'LOGIN',
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  attempts INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ip_address TEXT,
  user_agent TEXT
);
CREATE INDEX IF NOT EXISTS ix_whatsapp_otp_phone ON whatsapp_otp_codes(phone_number, purpose, created_at DESC);

CREATE TABLE IF NOT EXISTS business_online_shops (
  shop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  shop_name VARCHAR(200) NOT NULL,
  shop_code VARCHAR(40) NOT NULL,
  logo_url TEXT,
  address TEXT,
  contact_number VARCHAR(30),
  whatsapp_number VARCHAR(30),
  business_category VARCHAR(100),
  description TEXT,
  delivery_available BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  created_by BIGINT REFERENCES app_users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT ck_online_shop_status CHECK (status IN ('ACTIVE','INACTIVE','BLOCKED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_business_online_shops_public_id ON business_online_shops(public_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_business_online_shops_code ON business_online_shops(LOWER(shop_code)) WHERE is_deleted=FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS ux_business_online_shops_business ON business_online_shops(business_id) WHERE is_deleted=FALSE;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_business_online_shops_updated_at') THEN
  CREATE TRIGGER trg_business_online_shops_updated_at BEFORE UPDATE ON business_online_shops FOR EACH ROW EXECUTE FUNCTION set_updated_at();
END IF; END $$;

CREATE TABLE IF NOT EXISTS online_shop_orders (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  shop_id BIGINT NOT NULL REFERENCES business_online_shops(shop_id) ON DELETE CASCADE,
  business_id BIGINT NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  customer_name VARCHAR(150) NOT NULL,
  customer_phone VARCHAR(30) NOT NULL,
  customer_address TEXT,
  items JSONB NOT NULL DEFAULT '[]'::JSONB,
  total_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'NEW',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT ck_online_order_amount CHECK (total_amount >= 0),
  CONSTRAINT ck_online_order_status CHECK (status IN ('NEW','ACCEPTED','REJECTED','COMPLETED','CANCELLED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_online_shop_orders_public_id ON online_shop_orders(public_id);
CREATE INDEX IF NOT EXISTS ix_online_shop_orders_business_status ON online_shop_orders(business_id, status);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_online_shop_orders_updated_at') THEN
  CREATE TRIGGER trg_online_shop_orders_updated_at BEFORE UPDATE ON online_shop_orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
END IF; END $$;
